### ISSUE TITLE
question about the Table 2 in paper.

### ISSUE THREAD

**Issue by ywh187** [Yuliang-Liu/MultimodalOCR#25]
Hello! 
In the FULL_TEST.json file, the ChartQA dataset is divided into two parts: chartQA and ChartQA_Human, how to get the results of ChartQA in Table 2 of the paper? Thanks

**Comment by echo840** [comment]
Hello, it is the average of "ChartQA"(augmented) and "ChartQA_Human"(human).

**Comment by ywh187** [comment]
Thank you, I got it. 
I'm a bit confused about whether the FULL_TEST.json file contains the complete test set. It seems to be somewhat less than the complete test set. You mentioned in the document that you removed data with answers of less than 4 characters. Is that so?

**Comment by echo840** [comment]
Yes, that's right. Due to the open-ended nature of LMM's responses, the evaluation criteria of the original dataset may not be suitable in zero-shot scenarios. Therefore, we are using accuracy(whether the answer appears in the response) as the evaluation metric. To reduce false positives, we filtered out answers with fewer than 4 characters. Because answers with fewer than 4 characters are more likely to appear within other words or numbers.
